/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://wriafu3p2zb57j4ziazchty7ei.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2mfqkbmkg5a5tf3wlrc5lxnv3e",
    "aws_cognito_identity_pool_id": "eu-north-1:b2a5a54b-c7b6-4ebe-95f3-ee48509963fc",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_FMfsTZt6y",
    "aws_user_pools_web_client_id": "8ev58li6fqaffhse3s4qaol5g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
